{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from MaxCutProblem import MaxCutProblem"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "problem = MaxCutProblem()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Shutting down old Ray instance.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-05 15:04:29,351\tINFO worker.py:1810 -- Started a local Ray instance. View the dashboard at \u001b[1m\u001b[32m127.0.0.1:8265 \u001b[39m\u001b[22m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[('vanilla', 'uniform', True), ('vanilla', 'gaussian', True), ('multiangle', 'uniform', True), ('multiangle', 'gaussian', True)]\n",
      "Parameters: ('vanilla', 'uniform', True)\n",
      "\u001b[36m(parallell_runner pid=29996)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=31784)\u001b[0m You are running on the local simulator:  fake_brisbane\u001b[32m [repeated 15x across cluster]\u001b[0m\n",
      "\u001b[36m(parallell_runner pid=16396)\u001b[0m You are running on the local simulator:  fake_brisbane\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(parallell_runner pid=29996)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=33752)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=21412)\u001b[0m You are running on the local simulator:  fake_brisbane\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(parallell_runner pid=27288)\u001b[0m You are running on the local simulator:  fake_brisbane\u001b[32m [repeated 2x across cluster]\u001b[0m\n"
     ]
    },
    {
     "ename": "GetTimeoutError",
     "evalue": "Get timed out: some object(s) not ready.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mGetTimeoutError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[11], line 50\u001b[0m\n\u001b[0;32m     48\u001b[0m names \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mlist\u001b[39m(itertools\u001b[38;5;241m.\u001b[39mchain\u001b[38;5;241m.\u001b[39mfrom_iterable(names))\n\u001b[0;32m     49\u001b[0m futures \u001b[38;5;241m=\u001b[39m [parallell_runner\u001b[38;5;241m.\u001b[39mremote(parameters, graph, name) \u001b[38;5;28;01mfor\u001b[39;00m graph, name \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mzip\u001b[39m(graphs, names)]\n\u001b[1;32m---> 50\u001b[0m results \u001b[38;5;241m=\u001b[39m \u001b[43mray\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfutures\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m60\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m7\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m     51\u001b[0m underway_df \u001b[38;5;241m=\u001b[39m pd\u001b[38;5;241m.\u001b[39mDataFrame(ray\u001b[38;5;241m.\u001b[39mget(results))\n\u001b[0;32m     52\u001b[0m underway_df\u001b[38;5;241m.\u001b[39mto_csv(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mresults_underway.csv\u001b[39m\u001b[38;5;124m'\u001b[39m, mode\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124ma\u001b[39m\u001b[38;5;124m'\u001b[39m, header\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m)\n",
      "File \u001b[1;32mc:\\Users\\torbjsme\\Master\\QAOA\\myenv\\lib\\site-packages\\ray\\_private\\auto_init_hook.py:21\u001b[0m, in \u001b[0;36mwrap_auto_init.<locals>.auto_init_wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     18\u001b[0m \u001b[38;5;129m@wraps\u001b[39m(fn)\n\u001b[0;32m     19\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mauto_init_wrapper\u001b[39m(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[0;32m     20\u001b[0m     auto_init_ray()\n\u001b[1;32m---> 21\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m fn(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\torbjsme\\Master\\QAOA\\myenv\\lib\\site-packages\\ray\\_private\\client_mode_hook.py:103\u001b[0m, in \u001b[0;36mclient_mode_hook.<locals>.wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    101\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m func\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m \u001b[38;5;241m!=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124minit\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01mor\u001b[39;00m is_client_mode_enabled_by_default:\n\u001b[0;32m    102\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mgetattr\u001b[39m(ray, func\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m--> 103\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m func(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\torbjsme\\Master\\QAOA\\myenv\\lib\\site-packages\\ray\\_private\\worker.py:2753\u001b[0m, in \u001b[0;36mget\u001b[1;34m(object_refs, timeout)\u001b[0m\n\u001b[0;32m   2747\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[0;32m   2748\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mInvalid type of object refs, \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mtype\u001b[39m(object_refs)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m, is given. \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   2749\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mobject_refs\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m must either be an ObjectRef or a list of ObjectRefs. \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   2750\u001b[0m     )\n\u001b[0;32m   2752\u001b[0m \u001b[38;5;66;03m# TODO(ujvl): Consider how to allow user to retrieve the ready objects.\u001b[39;00m\n\u001b[1;32m-> 2753\u001b[0m values, debugger_breakpoint \u001b[38;5;241m=\u001b[39m \u001b[43mworker\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_objects\u001b[49m\u001b[43m(\u001b[49m\u001b[43mobject_refs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   2754\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m i, value \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28menumerate\u001b[39m(values):\n\u001b[0;32m   2755\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(value, RayError):\n",
      "File \u001b[1;32mc:\\Users\\torbjsme\\Master\\QAOA\\myenv\\lib\\site-packages\\ray\\_private\\worker.py:880\u001b[0m, in \u001b[0;36mWorker.get_objects\u001b[1;34m(self, object_refs, timeout, return_exceptions)\u001b[0m\n\u001b[0;32m    872\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[0;32m    873\u001b[0m             \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mAttempting to call `get` on the value \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mobject_ref\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    874\u001b[0m             \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mwhich is not an ray.ObjectRef.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    875\u001b[0m         )\n\u001b[0;32m    877\u001b[0m timeout_ms \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mint\u001b[39m(timeout \u001b[38;5;241m*\u001b[39m \u001b[38;5;241m1000\u001b[39m) \u001b[38;5;28;01mif\u001b[39;00m timeout \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m\n\u001b[0;32m    878\u001b[0m data_metadata_pairs: List[\n\u001b[0;32m    879\u001b[0m     Tuple[ray\u001b[38;5;241m.\u001b[39m_raylet\u001b[38;5;241m.\u001b[39mBuffer, \u001b[38;5;28mbytes\u001b[39m]\n\u001b[1;32m--> 880\u001b[0m ] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcore_worker\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_objects\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    881\u001b[0m \u001b[43m    \u001b[49m\u001b[43mobject_refs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    882\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcurrent_task_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    883\u001b[0m \u001b[43m    \u001b[49m\u001b[43mtimeout_ms\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    884\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    886\u001b[0m debugger_breakpoint \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mb\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    887\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m data, metadata \u001b[38;5;129;01min\u001b[39;00m data_metadata_pairs:\n",
      "File \u001b[1;32mpython\\ray\\_raylet.pyx:3484\u001b[0m, in \u001b[0;36mray._raylet.CoreWorker.get_objects\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32mpython\\ray\\includes/common.pxi:81\u001b[0m, in \u001b[0;36mray._raylet.check_status\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mGetTimeoutError\u001b[0m: Get timed out: some object(s) not ready."
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36m(parallell_runner pid=22688)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=11452)\u001b[0m You are running on the local simulator:  fake_brisbane\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(parallell_runner pid=26072)\u001b[0m You are running on the local simulator:  fake_brisbane\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(parallell_runner pid=22268)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=16396)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=33752)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=27288)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=31784)\u001b[0m You are running on the local simulator:  fake_brisbane\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(parallell_runner pid=6776)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=26924)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=18928)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=21412)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=22688)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=3228)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=22268)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=21044)\u001b[0m You are running on the local simulator:  fake_brisbane\n",
      "\u001b[36m(parallell_runner pid=11452)\u001b[0m You are running on the local simulator:  fake_brisbane\n"
     ]
    }
   ],
   "source": [
    "import itertools\n",
    "import time\n",
    "import params\n",
    "from QAOA import QAOArunner\n",
    "from datetime import date\n",
    "import pandas as pd\n",
    "from solver import Solver\n",
    "import ray\n",
    "\n",
    "\n",
    "@ray.remote\n",
    "def parallell_runner(parameters, graph,name):\n",
    "    qaoa = QAOArunner(graph, simulation=True, param_initialization=parameters[1],qaoa_variant=parameters[0], warm_start=parameters[2])\n",
    "    qaoa.build_circuit()\n",
    "    qaoa.run()\n",
    "    solver = Solver(graph)\n",
    "    bitstring, value = solver.solve()\n",
    "    return {'param_initialization': parameters[1], 'qaoa_variant': parameters[0], 'warm_start' : parameters[2],\n",
    "        'depth': params.depth, 'graph_size': len(graph.nodes()), 'graph_name' : name,\n",
    "        'time_elapsed': qaoa.time_elapsed, 'quantum_func_evals': qaoa.fev, 'obj_func_evolution': qaoa.objective_func_vals,\n",
    "        'quantum_solution':qaoa.solution, 'quantum_obj_value' : qaoa.evaluate_sample(), \n",
    "        'classic_solution' : bitstring, 'classic_value': value }\n",
    "if ray.is_initialized():\n",
    "    ray.shutdown()\n",
    "    print('Shutting down old Ray instance.')\n",
    "ray.init(num_cpus=15)\n",
    "\n",
    "iterables = [params.supported_qaoa_variants, params.supported_param_inits, [True]] #TODO: change to only gaussian inits\n",
    "settings = list(itertools.product(*iterables))\n",
    "print(settings)\n",
    "\n",
    "#settings = [('multiangle', 'gaussian', True),('vanilla', 'uniform', True), ('vanilla', 'gaussian', True), ('multiangle', 'uniform', True),('multiangle', 'gaussian', True)] \n",
    "\n",
    "data = []\n",
    "# Reset results_underway.csv file\n",
    "with open('results_underway.csv', 'w') as f:\n",
    "    f.write('index,param_initialization,qaoa_variant,warm_start,depth,graph_size,graph_name,time_elapsed,quantum_func_evals,quantum_solution,quantum_obj_value,classic_solution,classic_value,obj_func_evolution,\\n')\n",
    "\n",
    "for parameters in settings:\n",
    "    print('Parameters:', parameters)\n",
    "    graphs = []\n",
    "    names = []\n",
    "    for i in range(5,10):\n",
    "        graphs_i, names_i = problem.get_test_graphs(i)\n",
    "        graphs.append(graphs_i) #TODO: check that this works for very small values\n",
    "        names.append(names_i)\n",
    "    graphs = list(itertools.chain.from_iterable(graphs))\n",
    "    names = list(itertools.chain.from_iterable(names))\n",
    "    futures = [parallell_runner.remote(parameters, graph, name) for graph, name in zip(graphs, names)]\n",
    "    results = ray.get(futures)\n",
    "    underway_df = pd.DataFrame(ray.get(results))\n",
    "    underway_df.to_csv(f'results_underway.csv', mode='a', header=False)\n",
    "    data.extend(results)\n",
    "    print(f'Done with Parameters: {parameters} at time: {time.time()}')\n",
    "df = pd.DataFrame(data)\n",
    "df.to_csv(f'results_.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "RayTaskError(IndexError)",
     "evalue": "\u001b[36mray::parallell_runner()\u001b[39m (pid=26928, ip=127.0.0.1)\n  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_3568\\852041552.py\", line 13, in parallell_runner\nIndexError: list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRayTaskError(IndexError)\u001b[0m                  Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[4], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m results \u001b[38;5;241m=\u001b[39m \u001b[43mray\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfutures\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m      2\u001b[0m underway_df \u001b[38;5;241m=\u001b[39m pd\u001b[38;5;241m.\u001b[39mDataFrame(results)\n\u001b[0;32m      3\u001b[0m underway_df\u001b[38;5;241m.\u001b[39mto_csv(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mresults_underway.csv\u001b[39m\u001b[38;5;124m'\u001b[39m, mode\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124ma\u001b[39m\u001b[38;5;124m'\u001b[39m, header\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m)\n",
      "File \u001b[1;32mc:\\Users\\torbjsme\\Master\\QAOA\\myenv\\lib\\site-packages\\ray\\_private\\auto_init_hook.py:21\u001b[0m, in \u001b[0;36mwrap_auto_init.<locals>.auto_init_wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     18\u001b[0m \u001b[38;5;129m@wraps\u001b[39m(fn)\n\u001b[0;32m     19\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mauto_init_wrapper\u001b[39m(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[0;32m     20\u001b[0m     auto_init_ray()\n\u001b[1;32m---> 21\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m fn(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\torbjsme\\Master\\QAOA\\myenv\\lib\\site-packages\\ray\\_private\\client_mode_hook.py:103\u001b[0m, in \u001b[0;36mclient_mode_hook.<locals>.wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    101\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m func\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m \u001b[38;5;241m!=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124minit\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01mor\u001b[39;00m is_client_mode_enabled_by_default:\n\u001b[0;32m    102\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mgetattr\u001b[39m(ray, func\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m--> 103\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m func(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\torbjsme\\Master\\QAOA\\myenv\\lib\\site-packages\\ray\\_private\\worker.py:2753\u001b[0m, in \u001b[0;36mget\u001b[1;34m(object_refs, timeout)\u001b[0m\n\u001b[0;32m   2747\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[0;32m   2748\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mInvalid type of object refs, \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mtype\u001b[39m(object_refs)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m, is given. \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   2749\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mobject_refs\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m must either be an ObjectRef or a list of ObjectRefs. \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   2750\u001b[0m     )\n\u001b[0;32m   2752\u001b[0m \u001b[38;5;66;03m# TODO(ujvl): Consider how to allow user to retrieve the ready objects.\u001b[39;00m\n\u001b[1;32m-> 2753\u001b[0m values, debugger_breakpoint \u001b[38;5;241m=\u001b[39m \u001b[43mworker\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_objects\u001b[49m\u001b[43m(\u001b[49m\u001b[43mobject_refs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   2754\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m i, value \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28menumerate\u001b[39m(values):\n\u001b[0;32m   2755\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(value, RayError):\n",
      "File \u001b[1;32mc:\\Users\\torbjsme\\Master\\QAOA\\myenv\\lib\\site-packages\\ray\\_private\\worker.py:904\u001b[0m, in \u001b[0;36mWorker.get_objects\u001b[1;34m(self, object_refs, timeout, return_exceptions)\u001b[0m\n\u001b[0;32m    902\u001b[0m     global_worker\u001b[38;5;241m.\u001b[39mcore_worker\u001b[38;5;241m.\u001b[39mdump_object_store_memory_usage()\n\u001b[0;32m    903\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(value, RayTaskError):\n\u001b[1;32m--> 904\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m value\u001b[38;5;241m.\u001b[39mas_instanceof_cause()\n\u001b[0;32m    905\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    906\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m value\n",
      "\u001b[1;31mRayTaskError(IndexError)\u001b[0m: \u001b[36mray::parallell_runner()\u001b[39m (pid=26928, ip=127.0.0.1)\n  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_3568\\852041552.py\", line 13, in parallell_runner\nIndexError: list index out of range"
     ]
    }
   ],
   "source": [
    "results = ray.get(futures)\n",
    "underway_df = pd.DataFrame(results)\n",
    "underway_df.to_csv(f'results_underway.csv', mode='a', header=False)\n",
    "data.extend(results)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=19776, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=27056, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=13200, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=19776, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=13200, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=13200, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=23684, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=22228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=16256, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=7400, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=25540, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=24236, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n",
      "Task failed with error: \u001b[36mray::parallell_runner()\u001b[39m (pid=1828, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\torbjsme\\AppData\\Local\\Temp\\ipykernel_28600\\245689880.py\", line 15, in parallell_runner\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 224, in run\n",
      "    init_params = self.get_init_params()\n",
      "  File \"c:\\Users\\torbjsme\\Master\\QAOA\\QAOA.py\", line 206, in get_init_params\n",
      "    init_params = np.array([[np.random.normal(np.pi,0.2,param_cost_length), (np.random.normal(np.pi/2,0.2,param_mixer_length))] for i in range(params.depth)])\n",
      "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.\n"
     ]
    }
   ],
   "source": [
    "results2 = []\n",
    "for task in futures:\n",
    "    try:\n",
    "        result = ray.get(task)  # Retrieve the result\n",
    "        results2.append(result)  # Store in local memory\n",
    "    except Exception as e:\n",
    "        print(f\"Task failed with error: {e}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "myenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
